# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: |
          (?x)^(
            charts/.*/templates/.*|
            mkdocs.yml
          )$
        args:
          - --multi
      - id: check-added-large-files
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.5
    hooks:
      - id: gofumpt
        types: [go]
        exclude: ".*/zz_generated.*\\.go$"
  - repo: local
    hooks:
      - id: generate-deep-copy
        name: generated deep-copy code must be up-to-date
        language: system
        pass_filenames: false
        entry: make manifests
      - id: golangci-lint
        name: Run golangci-lint
        types: [go]
        language: system
        pass_filenames: false
        entry: golangci-lint run --new-from-rev=HEAD
      - id: run-tests
        name: Run go tests
        language: system
        pass_filenames: false
        entry: make test
      - id: sync-chart
        name: Run make sync-chart
        language: system
        pass_filenames: false
        entry: make sync-chart
      - id: check-docs
        name: check docs builds
        language: system
        pass_filenames: false
        entry: mkdocs build -s
